### ISSUE TITLE
Steps/validation don't seem to remember information

### ISSUE THREAD

**Issue by Mark-H** [Sterc/formalicious#14]
Create a two step form. Fill in fields in step 1. Click next. Click prev. Empty fields :(

**Comment by sepiariver** [comment]
+1 on this issue. Pretty amazing start though!

**Comment by Bumme** [comment]
@Mark-H The snippets "FormaliciousGetValues" and "FormaliciousSaveValues" does they exists?

**Comment by sepiariver** [comment]
They do in my install

YJ Tso

Pecked on a tiny keyboard.

**Comment by matdave** [comment]
Sooo, do we need to include those two snippets in order for multi-step forms to save values.  When I submit the form it doesn't email the first steps.

**Comment by pixelive** [comment]
Hello,

This should be fixed with the following transport file:

https://github.com/Sterc/formalicious/blob/master/formalicious-0.5.2-beta.transport.zip

**Comment by matdave** [comment]
Seems like it's still not remembering steps.  At least it didn't remember the fields when I hit the "Previous" button on the second step.

**Comment by pixelive** [comment]
Hello @matdave,

Does the `FormaliciousSaveValues` snippet contain the following code?

<?php
$formit =& $hook->formit;
$values = $hook->getValues();
$oldValues = $_SESSION['Formalicious_form_'.$formit->config['formid']];
if(!$oldValues) $oldValues = array();
$_SESSION['Formalicious_form_'.$formit->config['formid']] = array_merge($oldValues, $values);
$hook->setValues(array_merge($oldValues, $values));
return true;
?>

The following line could be missing:

$hook->setValues(array_merge($oldValues, $values));

**Comment by matdave** [comment]
@pixelive sorry for the long delay, got stuck in production.  Yes the snippet looks like that.  

https://www.ideabankmarketing.com/test-form2.html

my code is just 
<pre>[[!renderForm? &form=`[[*formalicious]]`]]</pre>

I have cacheable unchecked on the settings tab.  It just doesn't remember the first step for some reason.

**Comment by matdave** [comment]
Update, I uninstalled and reinstalled the module.  It doesn't remember the first set still on the frontend when clicking next and previous, but it DOES email the correct values!
